version: "3.6"
services:
  postgres:
    container_name: vroda_pg
    image: postgres:15
    restart: always
    volumes:
      - vroda_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    container_name: vroda_hasura
    image: hasura/graphql-engine:v2.29.0
    ports:
      - "8081:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@vroda_pg:5432/postgres
      PG_DATABASE_URL: postgres://postgres:postgrespassword@vroda_pg:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: mydminsecretkeyvroda
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: guest
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key":"rorjnwVXlNoSsC216738zr4iLx9fxGbB"}'
      HASURA_ACTIONS_ENDPOINT: http://host.docker.internal:8888/.netlify/functions
      # HASURA_PIZZASTACK_SECRET: mysecondadminsecretkeyvroda
      HASURA_EVENT_WEBHOOK_HANDLER: http://host.docker.internal:8888/.netlify/functions/hasura-webhook
      HASURA_VRODA_SECRET: myvrodasicretkey
volumes:
  vroda_db_data:
